name: Jamiie
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider:
  http:
  http_parser: ^3.1.4
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.7+4
  numeric_keyboard: ^1.0.0
  shared_preferences: ^0.5.8
  data_connection_checker: ^0.3.4
  cached_network_image: ^2.2.0+1
  lottie: ^0.5.1
  share: ^0.6.4+3
  auto_size_text: ^2.1.0
  path: ^1.7.0
  firebase_messaging: ^7.0.0
  path_provider: ^1.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.jpeg
    - assets/LOGO1.jpg
    - assets/logo3.png
    - assets/money.json
    - assets/loader.json
    - assets/fonts/
    - assets/Json/adminPool.json
    - assets/Json/dashboard.json
    - assets/Json/joinPool.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
