name: Jamiie
description: A project made for project Jamiie

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider:
  http:
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.7+4
  numeric_keyboard: ^1.0.0
  shared_preferences: ^0.5.8
  crypto: ^2.1.4
  data_connection_checker: ^0.3.4
  google_sign_in: ^4.5.1
  flutter_svg: ^0.18.0
  share: ^0.6.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.jpeg
    - assets/LOGO1.jpg
    - assets/logo3.png
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
