# Generated by Django 3.1 on 2020-08-17 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePool',
            fields=[
                ('poolid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('poolname', models.CharField(max_length=255)),
                ('poolamount', models.FloatField()),
                ('deadline', models.DateField()),
                ('pooltype', models.CharField(max_length=255)),
                ('minmember', models.CharField(max_length=255)),
                ('maxmember', models.CharField(max_length=255)),
                ('joinedmember', models.CharField(max_length=255, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('poolowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poolowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
