# Generated by Django 3.1 on 2020-08-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePool',
        ),
    ]
