# Generated by Django 3.1 on 2020-09-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpool',
            name='contributionAmount',
            field=models.IntegerField(),
        ),
    ]
