# Generated by Django 3.1 on 2020-08-18 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinedat', models.DateTimeField(auto_now_add=True)),
                ('memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joinedmember', to=settings.AUTH_USER_MODEL)),
                ('poolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joinedpool', to='pool.createpool')),
            ],
        ),
        migrations.DeleteModel(
            name='TestPool',
        ),
    ]
