# Generated by Django 3.1 on 2020-08-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpool',
            old_name='poolAmount',
            new_name='contributionAmount',
        ),
        migrations.RenameField(
            model_name='createpool',
            old_name='maxMember',
            new_name='totalMember',
        ),
        migrations.RemoveField(
            model_name='createpool',
            name='minMember',
        ),
    ]
