# Generated by Django 3.1 on 2020-08-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_createpool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpool',
            name='joinedmember',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='createpool',
            name='maxmember',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createpool',
            name='minmember',
            field=models.IntegerField(),
        ),
    ]
