# Generated by Django 3.1 on 2020-08-21 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('securityNumber', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('otp', models.CharField(max_length=255, unique=True)),
                ('validated', models.BooleanField()),
                ('register', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RiskCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobAge', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('savingMoney', models.CharField(max_length=255)),
                ('loans', models.CharField(max_length=255)),
                ('living', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobAge', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('savingMoney', models.CharField(max_length=255)),
                ('loans', models.CharField(max_length=255)),
                ('living', models.CharField(max_length=255)),
                ('riskScore', models.IntegerField(null=True)),
                ('riskBand', models.CharField(max_length=255)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
