# Generated by Django 3.1 on 2020-09-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20200825_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileId', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
