# Generated by Django 3.1 on 2020-09-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
