# Generated by Django 3.1 on 2020-09-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='family',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='jobAge',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='living',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='loans',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='savingMoney',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='riskBand',
            field=models.CharField(default='Moderate', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='riskScore',
            field=models.IntegerField(default=56, null=True),
        ),
    ]
